import type { Metadata } from "next";
import { CtaBand, PageHero, ProofList, SiteShell } from "@/components/Marketing";
export const metadata: Metadata = { title: "Compare CuroPay", description: "Compare CuroPay with cashier’s checks, money orders, Venmo, Zelle, and True Link." };
const comparisons=[
  {title:"CuroPay vs. cashier’s checks & money orders",text:"The same familiar artifact — without the trip, the exposed account details, or the fraud risk.",other:"Cashier’s checks & money orders",them:["A trip to the bank or store, and a fee, every time","Account and routing numbers printed in the open","No way to verify who’s really sending or receiving","Vulnerable to mail theft and loss"],us:["Print at home, mail, or send instantly — no trip","Account and routing numbers are never exposed","Identity-verified and funds-certified on every check","QR-backed, so a stolen check can’t simply be cashed"]},
  {title:"CuroPay vs. Venmo & Zelle",text:"Instant P2P is fine between friends. It was never built to move money for someone else, with proof.",other:"Venmo / Zelle",them:["No co-signing and no role-based approvals","No identity verification of the other party","Designed for people you already trust","Little recourse if something goes wrong"],us:["Co-signing and role-based approvals built in","Identity verified on both sides of the transfer","Certified funds — proof, not just a promise","A real receipt and audit trail on every payment"]},
  {title:"CuroPay vs. True Link",text:"The closest option built for this job — but a different tool. True Link is a prepaid card; CuroPay is a certified payment rail.",other:"True Link (prepaid card)",them:["A prepaid-card model, built around card spending","Not designed for recurring bill-pay, rent, or reimbursement","No printable, mailable check for those who still need one"],us:["A certified check / payment rail, not a card","Built for recurring bill-pay, rent, and reimbursement","Keeps the printable, QR-backed check people still rely on","Approvals and an audit trail for fiduciary use"]}
];
export default function ComparePage(){return <SiteShell active="/compare"><PageHero eyebrow="Compare" title="How CuroPay compares to what you use today." description="The same familiar check — but identity-verified, funds-certified, and built with the proof and control the alternatives leave out." />
 <section className="section"><div className="wrap comparison-stack">{comparisons.map(c=><article className="comparison" key={c.title}><header className="comparison-title"><h2>{c.title}</h2><p>{c.text}</p></header><div className="comparison-cols"><div className="comparison-col"><h3>{c.other}</h3><ProofList items={c.them}/></div><div className="comparison-col"><h3>CuroPay</h3><ProofList items={c.us}/></div></div></article>)}</div></section>
 <section className="section compact navy"><div className="wrap"><p className="lede">Paper checks and money orders mean fraud, delays, and exposed account numbers. P2P apps offer no verification and no recourse. CuroPay is built to move the money itself — <strong>certified, verified, and controlled.</strong></p></div></section>
 <CtaBand title="See the difference on your next payment." text="Move money the way you already do — with proof and control the alternatives don’t offer." /></SiteShell>}
