import type { Metadata } from "next";
import Link from "next/link";
import { CtaBand, FeatureCards, PageHero, ProductStory, SectionHeading, SiteShell, registerUrl } from "@/components/Marketing";
export const metadata: Metadata = { title: "For Caregivers & Fiduciaries | CuroPay", description: "Move money for someone else with role-based approvals, certified funds, and an audit-ready record." };
export default function CaregiversPage(){return <SiteShell active="/caregivers">
  <PageHero eyebrow="Caregivers & fiduciaries" title="Move money for someone else, with proof and control." description="If your attorney, CPA, or bank pointed you here — you’re in the right place. CuroPay is built for trustees, POAs, and caregivers who move money on someone else’s behalf and have to account for every dollar." image="/curo-lp-hero-image.png"><Link className="button button-primary button-large" href={registerUrl}>Create your account</Link></PageHero>
  <section className="section"><div className="wrap"><SectionHeading eyebrow="Accountability built in" title="Everything a fiduciary needs, built into the transfer." center /><FeatureCards items={[
    {icon:"✓",title:"Role-based approvals & thresholds",text:"Set who can approve, who can only view, and the dollar amount that requires sign-off. Funds never move without the right approval."},
    {icon:"≡",title:"Audit-ready receipts",text:"Every payment produces the record your attorney and CPA can act on — no more stitching together cashier’s checks, email threads, and shared folders."},
    {icon:"ID",title:"Identity & funds certification",text:"Both are verified and certified on every transfer, before the money moves — the proof and recourse paper checks and P2P apps lack."}
  ]}/></div></section>
  <section className="section compact"><div className="wrap"><div className="objection"><h2>“Is this safe and legitimate?”</h2><div><p><strong>The concern</strong>You’re moving money that isn’t yours, and you may have to defend the decision later. It has to be safe and legitimate enough for a trust, an attorney, and the IRS.</p><p><strong>The answer</strong>Certified funds, verified identity, and an audit trail are built into every transfer — not bolted on afterward. The money is accounted for before anyone has to ask.</p></div></div></div></section>
  <section className="section tint"><div className="wrap story-stack"><ProductStory image="/curo-lp-how-it-works-3.png" eyebrow="A cleaner workflow" title="Replace the cashier’s checks, email threads, and shared folders." text="Coordinate recurring outflows — home care, rent, prescriptions — and one-off expenses, while staying accountable to siblings, attorneys, and CPAs. Approval happens before the money moves." caption="Audit-ready receipts — every payment produces the record your attorney and CPA can act on." /><ProductStory image="/curo-lp-how-it-works-1.png" eyebrow="Shared responsibility" title="Keep siblings and co-trustees in the loop." text="Add the people who share the responsibility as owners, co-payers, or view-only. Each one sees what’s shared and what cleared — so nobody’s left guessing, and no change happens one-sided." flip /></div></section>
  <section className="section"><div className="wrap"><SectionHeading eyebrow="Trusted referrals" title="A recommendation they can stand behind." description="Are you an elder-law attorney, POA, CPA, or community bank sending a client here?" /><Link className="button button-outline" href="/partners">See our partner program</Link></div></section>
  <CtaBand title="Set up approvals for your family’s money." text="Get the controls, the certification, and the record — in one account you can share with the people who need to see it." />
 </SiteShell>}
