import type { Metadata } from "next";
import Link from "next/link";
import LeadForm from "@/components/LeadForm";
import { FeatureCards, PageHero, ProofList, SectionHeading, SiteShell } from "@/components/Marketing";
export const metadata: Metadata = { title: "Partner with CuroPay", description: "Help clients and members move money safely through a CuroPay referral or co-marketing partnership." };
export default function PartnersPage(){return <SiteShell><PageHero eyebrow="For attorneys, fiduciaries, CPAs & financial institutions" title="Protect the clients who trust you — and grow the relationship while you do it." description="CuroPay is a certified digital-check platform for the caregivers, fiduciaries, and older clients you already serve. Recommend it with confidence, cut the fraud and paperwork that lands back on your desk, and stay the name your clients count on."><Link className="button button-primary button-large" href="#partner-form">Explore partnership</Link><Link className="button button-outline button-large" href="#partner-form">Refer a client</Link></PageHero>
 <section className="section tint"><div className="wrap"><SectionHeading eyebrow="Two ways to partner" title="Built around what you’re trying to do." description="Whether you advise families or serve members, the partnership starts from your goal — not our product." /><div className="feature-grid cols-2"><article className="content-card"><p className="eyebrow">Attorneys, fiduciaries & CPAs</p><h2>Give clients a defensible way to move money.</h2><p>Protect clients and keep clean, defensible records — without the work landing back on your desk.</p><ProofList items={["Every transfer arrives audit-ready","Role-based approvals and thresholds create a defensible trail","Concierge onboarding handles the client’s first transfer","A fraud-protected recommendation deepens trust"]}/><Link className="button button-primary" href="#partner-form">Become a referral partner</Link></article><article className="content-card"><p className="eyebrow">Community banks & credit unions</p><h2>Offer families a safer check — without building it.</h2><p>Deepen relationships with aging members and their families, and cut the fraud losses that come with paper.</p><ProofList items={["A modern, certified-check capability you didn’t have to build","QR-backed checks help cut mail-theft and forged-check risk","Payouts can settle by ACH","Co-branded materials position your branch as the safe choice"]}/><Link className="button button-primary" href="#partner-form">Start a conversation</Link></article></div></div></section>
 <section className="section"><div className="wrap"><SectionHeading eyebrow="A partnership that works both ways" title="Everyone gains — including the client in the middle." center /><FeatureCards columns={2} items={[{icon:"♥",title:"What your clients get",text:"Safer payments, human support, and proof on every transfer — from a name they already trust: yours."},{icon:"↗",title:"What you get",text:"Stronger relationships, fewer fraud headaches, and a service you can stand behind — at no cost to recommend."}]}/></div></section>
 <section className="section tint"><div className="wrap"><SectionHeading eyebrow="How it works" title="Referral & co-marketing, kept simple." center /><div className="steps"><article className="step"><h3>Refer or introduce</h3><p>Share a co-branded link or printed hand-off card. Clients land on a page written for someone arriving through a trusted advisor.</p></article><article className="step"><h3>We onboard your client</h3><p>Guided setup and concierge phone support walk your client through their first transfer, so the work doesn’t come back to your office.</p></article><article className="step"><h3>Grow together</h3><p>Optional joint materials for your office, branch, or seminars — plus referral tracking and elder-fraud education.</p></article></div></div></section>
 <section className="section"><div className="wrap feature-grid cols-2"><div><SectionHeading eyebrow="What to tell a client" title="A recommendation you can make with confidence." /><p className="lede">CuroPay gives clients proof and control built into the transfer — the accountability you’d want documented for the annual accounting.</p></div><div className="quote-panel"><p>“CuroPay lets you move money on someone else’s behalf with approvals, verified identity, and an audit-ready record on every transfer.”</p></div></div></section>
 <section className="section tint" id="partner-form"><div className="wrap contact-grid"><div><SectionHeading eyebrow="Partner with us" title="Let’s build a referral relationship." description="Tell us about your clients or members and we’ll take it from there." /><ProofList items={["Free to recommend","No quotas or lock-in","Human onboarding support","Co-branded materials available"]}/></div><div className="form-card"><LeadForm kind="partner" /></div></div></section>
 </SiteShell>}
