import type { Metadata } from "next";
import Link from "next/link";
import { CtaBand, FeatureCards, PageHero, SectionHeading, SiteShell, registerUrl } from "@/components/Marketing";
export const metadata: Metadata = { title: "A Safer Check for Seniors | CuroPay", description: "Print or mail the check you know, now protected by verified identity and a secure QR code." };
export default function SeniorsPage(){return <SiteShell active="/seniors">
  <PageHero eyebrow="For people who trust checks" title="The same check you trust — just safer." description="Keep sending checks exactly the way you always have. Print one, mail it, or hand it over — now with a verified identity behind every one, and a real person to call if anything is unclear." image="/curo-lp-hero-image.png"><Link className="button button-primary button-large" href={registerUrl}>Create your account</Link></PageHero>
  <section className="section tint"><div className="wrap"><SectionHeading eyebrow="How it works" title="Three simple steps." center /><div className="steps"><article className="step"><h3>Write your check</h3><p>Enter who it’s for and the amount. Your account number stays private — it’s never printed on the check.</p></article><article className="step"><h3>Print or mail it</h3><p>Print it at home and mail it, or hand it over in person. Each check has a QR mark that proves it’s real.</p></article><article className="step"><h3>Know it arrived</h3><p>You’ll see a clear confirmation when it’s claimed. No more wondering whether it cleared.</p></article></div></div></section>
  <section className="section"><div className="wrap"><SectionHeading eyebrow="Built-in protection" title="What every CuroPay check gives you." center /><FeatureCards items={[{icon:"QR",title:"A printable, QR-backed check",text:"The familiar paper artifact you already trust — now with a secure code that proves it’s genuine."},{icon:"ID",title:"Verified identity",text:"Every check is tied to a verified identity, so a stolen check can’t simply be cashed by someone else."},{icon:"☎",title:"A real person to call",text:"Not sure about something? Call and talk to a person. We’ll walk you through it, step by step."}]}/></div></section>
  <section className="section compact"><div className="wrap"><div className="objection"><h2>“Is this still safe, the way a check is safe?”</h2><div><p><strong>A fair question</strong>You’ve trusted checks your whole life. You want to know this is the same thing — not a confusing new app that could go wrong.</p><p><strong>Yes — and safer</strong>It’s the same familiar check you already know how to use. The difference is that it’s fraud-protected and identity-verified. And a real person is one phone call away.</p></div></div></div></section>
  <CtaBand title="Print your first verified check." text="Keep the check you trust. Add the protection it never had." label="Get started" />
 </SiteShell>}
