import type { Metadata } from "next";
import { CtaBand, PageHero, SectionHeading, SiteShell } from "@/components/Marketing";
export const metadata: Metadata = { title: "CuroPay Fees", description: "Simple, transparent CuroPay fees. Bank-funded checks and standard ACH payouts are free." };
const fees=[["Bank-funded check","Fund a check from a linked bank account (ACH)","Free","—"],["Card-funded check","Fund a check with a debit or prepaid card","2.9% + $0.30","Sender, when funding by card"],["Standard payout","Recipient receives funds by ACH","Free","—"],["Instant payout","Recipient chooses instant delivery to a debit card","1.5%","Recipient — deducted from their payment"],["CuroPay Wallet payout","Coming soon — recipient keeps funds in a CuroPay Wallet","Free","Recipient"],["Physical check delivery","Pricing coming soon — we print and mail a check","Not yet published","Shown before you confirm"]];
const faqs=[["Is there a signup or monthly fee?","No. There’s no signup fee, monthly fee, or subscription. You only pay when you choose a card-based or instant option."],["Are there any hidden fees?","No. Every fee is shown before you confirm a payment, so you always see the exact cost up front."],["What’s the cheapest way to send?","Fund the check from a linked bank account and let the recipient take a standard ACH payout. Both are free."],["Who pays the instant-payout fee?","The recipient. The 1.5% is deducted only if they choose instant delivery to a debit card. Standard payout is free."],["What about physical check delivery?","We’re not publishing that fee yet. When it’s available, you’ll see the exact cost before confirming."]];
export default function PricingPage(){return <SiteShell><PageHero eyebrow="Fees" title="Simple, transparent fees." description="Send by bank for free. Pay only when using card-based or faster payment options." />
 <section className="section"><div className="wrap"><div className="feature-grid cols-2" style={{marginBottom:32}}><article className="content-card"><h2>$0 to send by bank</h2><p>Bank-funded checks and standard ACH payouts are always free.</p></article><article className="content-card"><h2>No subscriptions</h2><p>No monthly plans and no signup fee — you only pay per transaction when you choose a card or instant option.</p></article></div><div className="fees-wrap"><table className="fees"><thead><tr><th>Method</th><th>Fee</th><th>Who pays</th></tr></thead><tbody>{fees.map(([name,note,fee,payer])=><tr key={name}><td><strong>{name}</strong><small>{note}</small></td><td className={fee==="Free"?"free":""}>{fee}</td><td>{payer}</td></tr>)}</tbody></table></div><p className="trust-line">Fees are shown before confirmation and may change.</p></div></section>
 <section className="section tint"><div className="wrap"><SectionHeading eyebrow="Questions about fees" title="No signup, monthly, or hidden fees." center /><div className="faq">{faqs.map(([q,a])=><article key={q}><h3>{q}</h3><p>{a}</p></article>)}</div></div></section>
 <CtaBand title="Start sending for free." text="Send by bank at no cost, and pay only when you choose a card or instant option." />
 </SiteShell>}
